### PR TITLE
Added ViT and fixed a typo

### PR DESCRIPTION
**Pull request by bugraaldal**

### CODE REVIEW

**Comment by osbm** [comment]
goddamn
image

**Review by osbm — CHANGES_REQUESTED** [review]
filename should be in double underscore

**Comment by bugraaldal** [comment]
> filename should be in double underscore

Sorry about that, I overlooked.   
Also,
The commit we have we have been waiting for 2 months.

**Comment by osbm** [comment]
gotta speed it up.
i will work on a priority list for it

**Pull request merged**
